### ISSUE TITLE
Cordova - Android cannot find CheckoutActivity 

### ISSUE THREAD

**Issue by karanayyana** [razorpay/razorpay-cordova#23]
Hi,

I am using razorpay payment with my cordova application. supporting iOS and Android.
after following the instructions which is fairly simple, I was able to get it working on iOS but not Android.

It looks like in Android the installation is incomplete, It throws error cannot resolve symbol with "com.razorpay.CheckoutActivity", also i could not find any .jar file related to this unlike a framework that was for iOS.

**Comment by karanayyana** [comment]
i am using android studio 2.2

**Comment by karanayyana** [comment]
https://github.com/razorpay/razorpay-cordova-sample-app

I found an sample project from the above link.
after comparing I found the main.java I have and what was in the sample project is different.
However i could salvage razorpay-android.jar from the sample project, after addin it manually to my code I was able to compile.

I get this error when I launch payment. I am again clueless

 java.lang.NullPointerException: Attempt to read from field 'int java.lang.String.count' on a null object reference
 at java.lang.String.indexOf(String.java:1637)
at java.lang.String.indexOf(String.java:1616)
 at java.lang.String.indexOf(String.java:1596)
 at com.razorpay.CheckoutActivity$7.onPageFinished(:227)
 at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:531)
 at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:188)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by akshaybhalotia** [comment]
This has been stagnant for a long time, hence closing. Please feel free to re-open for further discussion.

**Comment by bhar-subhajit** [comment]
> Hi,
> 
> I am using razorpay payment with my cordova application. supporting iOS and Android. after following the instructions which is fairly simple, I was able to get it working on iOS but not Android.
> 
> It looks like in Android the installation is incomplete, It throws error cannot resolve symbol with "com.razorpay.CheckoutActivity", also i could not find any .jar file related to this unlike a framework that was for iOS.



Hi @karanayyana, Did you find the solution? I am also facing the same issue.
