### ISSUE TITLE
Issue during Cordova Compile

### ISSUE THREAD

**Issue by Purus** [razorpay/razorpay-cordova#7]
I am using this plugin along with Google AdMob plugin. It seems that there is a conflict of Jar files during compilation.

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
```

The admob plugin follows the standards for dependency but not this plugin as explained in the below link.
`
https://github.com/floatinghotpot/cordova-admob-pro/issues/164`

**Comment by Purus** [comment]
Issue due to another plugin. Please ignore.
